apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-dev
  namespace: devel
spec:
  selector:
    matchLabels:
      app: node-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: node-dev
    spec:
      restartPolicy: Always
      containers:
      - name: main
        image: jianshao/node-dev:lts-slim
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command: ['npm', '--prefix', '/home/devel/workspace', 'run', 'start']
        volumeMounts:
        - mountPath: /home/devel/workspace
          name: devel-workspace
      volumes:
      - name: devel-workspace
        persistentVolumeClaim:
          claimName: devel-workspace-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: node-dev
  namespace: devel
  labels:
    app: node-dev
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: node-dev
